import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children, title, actionBar }: { children: JSX.Element, title?: string, actionBar?: JSX.Element }) => (
    <>
        <Head>
            <title>{title || "SolidCRUD"}</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col bg-base-200">
            <Navbar title={title} actionBar={actionBar} />
            <div className="container mx-auto pt-4">
                {children}
            </div>
        </main>
    </>
)

export default Layout